
grade_hw_module: grade median Student_info
	g++ grade_hw_module.cc grade.o median.o Student_info.o -o grade_hw_module

grade:
	gcc -c grade.cc

median:
	gcc -c median.cc

Student_info:
	gcc -c Student_info.cc

clean:
	rm -rf *.o
	rm -rf grade_hw_module
